from __future__ import annotations

from typing import Protocol

from app.models.domain import Item, Role, StockEntry


class StoragePort(Protocol):
    def get_item(self, name: str) -> Item | None: ...

    def list_items(self, *, active_only: bool = True) -> list[Item]: ...

    def list_active_items(self) -> list[Item]: ...

    def add_item(self, name: str, *, norm: int, crit_min: int, qty: int, is_active: bool = True) -> None: ...

    def deactivate_item(self, name: str) -> None: ...

    def add_inbound(self, item: str, quantity: int, user_id: int, op_id: str | None = None) -> int: ...

    def add_outbound(self, item: str, quantity: int, user_id: int, op_id: str | None = None) -> int: ...

    def get_stock(self, item: str) -> int: ...

    def list_stock(self) -> list[StockEntry]: ...

    def get_item_limits(self, item: str) -> tuple[int | None, int | None]: ...

    def upsert_reorder_open(self, item: str, *, qty_now: int, norm: int, crit_min: int) -> None: ...

    def get_open_reorder(self, item: str): ...

    def upsert_user(self, user_id: int, name: str, role: Role, active: bool = True) -> None: ...

    def get_user_role(self, user_id: int) -> Role: ...
