from __future__ import annotations

from enum import Enum


class DialogState(str, Enum):
    IDLE = 'IDLE'
    WAITING_INBOUND = 'WAITING_INBOUND'
    WAITING_STOCK = 'WAITING_STOCK'
    TAKE_SELECT_ITEM = 'TAKE_SELECT_ITEM'
    TAKE_SELECT_QTY = 'TAKE_SELECT_QTY'
    TAKE_CONFIRM = 'TAKE_CONFIRM'
    ADD_ITEM_NAME = 'ADD_ITEM_NAME'
    ADD_ITEM_NORM = 'ADD_ITEM_NORM'
    ADD_ITEM_CRIT = 'ADD_ITEM_CRIT'
    ADD_ITEM_QTY = 'ADD_ITEM_QTY'
    USER_ADD_ID = 'USER_ADD_ID'
    USER_ADD_NAME = 'USER_ADD_NAME'
    USER_ADD_ROLE = 'USER_ADD_ROLE'
